# Generated by Django 6.0.5 on 2026-05-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('content_type', models.CharField(choices=[('all', 'All'), ('music', 'Music'), ('video', 'Video'), ('news', 'News'), ('instrumental', 'Instrumental')], default='all', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Blog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='Blog_catego_slug_37fc22_idx')],
            },
        ),
    ]
