# Generated by Django 6.0.5 on 2026-05-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.category'),
        ),
    ]
