# Generated by Django 6.0.5 on 2026-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_music_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='category',
        ),
        migrations.AddField(
            model_name='music',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='music', to='Blog.category'),
        ),
    ]
