# Generated by Django 6.0.5 on 2026-05-15 20:40
from django.db import migrations, models
from Blog.fields import SummernoteTextField


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_music_category_music_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', SummernoteTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='news', to='Blog.category')),
            ],
        ),
    ]
