# Generated by Django 6.0.5 on 2026-05-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
