# Generated by Django 6.0.5 on 2026-05-16 03:08
from django.db import migrations, models
from Blog.fields import SummernoteTextField


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='instrumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='instrumental/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='instrumental_images/')),
                ('description', SummernoteTextField()),
                ('released_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='instrumental', to='Blog.category')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='videos', to='Blog.category')),
            ],
        ),
    ]
