# Generated by Django 6.0.5 on 2026-05-16 03:38

import Blog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_instrumental_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='description',
            field=Blog.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=Blog.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=Blog.fields.SummernoteTextField(),
        ),
    ]
