# Generated by Django 6.0.5 on 2026-05-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_instrumental_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(),
        ),
    ]
