# Generated by Django 6.0.5 on 2026-05-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_music_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at']},
        ),
    ]
