# Generated by Django 6.0.5 on 2026-05-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_music_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Enter external audio URL (e.g., SoundCloud, YouTube, etc.)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
