# Generated by Django 6.0.5 on 2026-05-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_music_audio_url_alter_music_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(default='ENTERTAINMENT/media/cover_images/DJ-Tunez-STATE-OF-MIND-Artwork.jpg', upload_to='cover_images/'),
        ),
    ]
