# Generated by Django 6.0.5 on 2026-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_music_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
