# Generated by Django 6.0.5 on 2026-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_remove_news_content_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
