# Generated by Django 6.0.5 on 2026-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_alter_instrumental_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='News', to='Blog.category'),
        ),
    ]
