# Generated by Django 6.0.5 on 2026-05-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_remove_news_category_news_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categories',
            new_name='category',
        ),
    ]
