# Generated by Django 6.0.5 on 2026-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_rename_categories_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_tags',
            field=models.CharField(default='None', help_text='Enter tags separated by commas', max_length=200),
            preserve_default=False,
        ),
    ]
