# Generated by Django 6.0.5 on 2026-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_tags',
        ),
        migrations.AddField(
            model_name='music',
            name='music_tag',
            field=models.ManyToManyField(blank=True, help_text='Enter tags separated by commas', null=True, related_name='Music_Tags', to='Blog.tag'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_tags',
            field=models.ManyToManyField(blank=True, help_text='Enter tags separated by commas', null=True, related_name='Tags', to='Blog.tag'),
        ),
    ]
