# Generated by Django 6.0.5 on 2026-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_tag_remove_news_news_tags_music_music_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.CharField(choices=[('all', 'All'), ('music', 'Music'), ('video', 'Video'), ('news', 'News'), ('instrumental', 'Instrumental')], default='all', max_length=20),
        ),
    ]
