# Generated by Django 6.0.5 on 2026-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_tag_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_tag',
            field=models.ManyToManyField(blank=True, related_name='music_tags', to='Blog.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_tags',
            field=models.ManyToManyField(blank=True, help_text='Enter tags separated by commas', null=True, related_name='tags', to='Blog.tag'),
        ),
    ]
