# Generated by Django 6.0.5 on 2026-05-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_alter_music_music_tag_alter_news_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
