# Generated by Django 6.0.5 on 2026-05-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.music'),
        ),
    ]
