# Generated by Django 6.0.5 on 2026-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_alter_comment_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly. Leave blank if using a YouTube URL.', null=True, upload_to='videos/files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Enter a YouTube URL. Leave blank if uploading a video file.', null=True),
        ),
    ]
