# Generated by Django 6.0.5 on 2026-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_video_downloads_video_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the video.'),
        ),
    ]
