# Generated by Django 6.0.5 on 2026-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter a Direct Link to the video file.', null=True),
        ),
    ]
