# Generated by Django 6.0.5 on 2026-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0029_comment_video_alter_comment_music_alter_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_tags',
            field=models.ManyToManyField(blank=True, help_text='Enter tags separated by commas', related_name='tags', to='Blog.tag'),
        ),
    ]
