# Generated by Django 6.0.5 on 2026-05-24 20:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0030_alter_news_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
