# Generated by Django 6.0.5 on 2026-05-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0032_alter_instrumental_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumental',
            name='producer_name',
            field=models.CharField(default='Unknown Producer', max_length=150),
        ),
        migrations.AddField(
            model_name='instrumental',
            name='whatsapp',
            field=models.CharField(default='Unknown Whatsapp', help_text='Enter Whatsapp number (e.g., 234234234234)', max_length=20),
        ),
        migrations.AlterField(
            model_name='instrumental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
