# Generated by Django 6.0.5 on 2026-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0034_alter_instrumental_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='whatsapp',
            field=models.CharField(default='Unknown Whatsapp', help_text='Enter Whatsapp number (e.g., 234234234234)', max_length=30),
        ),
    ]
