# Generated by Django 6.0.5 on 2026-05-28 11:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0038_alter_instrumental_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='instrumental/'),
        ),
    ]
