# Generated by Django 6.0.5 on 2026-05-28 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0038_alter_instrumental_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, null=True, resource_type='auto', verbose_name='audio'),
        ),
    ]
