# Generated by Django 6.0.5 on 2026-05-28 22:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0040_alter_instrumental_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='instrumental/'),
        ),
        migrations.AlterField(
            model_name='instrumental',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='instrumental_images/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(default='ENTERTAINMENT/media/cover_images/DJ-Tunez-STATE-OF-MIND-Artwork.jpg', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file directly. Leave blank if using a YouTube URL.', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/files/'),
        ),
    ]
