# Generated by Django 6.0.5 on 2026-05-29 04:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0041_alter_instrumental_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumental',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
    ]
