# Generated by Django 6.0.5 on 2026-05-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0042_alter_instrumental_audio_file_alter_music_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumental',
            name='genre',
            field=models.CharField(blank=True, default='Afrobeat', max_length=100),
        ),
    ]
