# Generated by Django 6.0.5 on 2026-05-30 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0043_instrumental_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instrumental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_comments', to='Blog.instrumental'),
        ),
    ]
